# Site settings
name: More Than Java
email: liuhao.86@foxmail.com
author: Howard Liu
url: http://liuhao86.github.io
github: https://github.com/liuhao86/
stackoverflow: http://stackoverflow.com/users/6126931/liu-hao
baseurl: "https://liuhao86.github.io"
description: Java, and More than It.

permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: liuhao86

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems: [jekyll-paginate, jekyll-gist]

#baidu_analysis: 80ad9f91a7c35d83585bd396459451cf
baidu_analysis: 14bcd533ac6a0b38be4ee57a044b5a8d

FB:
  comments :
    provider : disqus
    disqus :
        short_name : liuhao86-github-io
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
